inflearn/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagram/', include('instagram.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

inflearn/instagram/urls.py
from django.urls import path, register_converter
from . import views
from .converters import YearConverter, MonthConverter, DayConverter

register_converter(YearConverter, 'year')
register_converter(MonthConverter, 'month')
register_converter(DayConverter, 'day')

app_name = 'instagram'  # URL Reverse에서 namespace역할을 하게 된다.

urlpatterns = [
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/delete/', views.post_delete, name='post_delete'),

    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('archive/', views.post_archive, name='post_archive'),
    path('archive/<year:year>/', views.post_archive_year, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/', views.post_archive_month, name='post_archive_year'),
    # path('archive/<year:year>/<month:month>/<day:day>/', views.post_archive_day, name='post_archive_year'),

]

inflearn/instagram/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.conf import settings
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(
        validators=[MinLengthValidator(10)]
    )
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    tag_set = models.ManyToManyField('Tag', blank=True)
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True) # auto_now_add : 최초 생성 시간을 1번 사용하여 저장, 갱신 불가능
    updated_at = models.DateTimeField(auto_now=True) # auto_now : 장고 모델이 저장될때마다 현재날짜(시간)으로 갱신, 갱신 가능

    def __str__(self):
        # return f"Custom Post object ({self.message})"
        return self.message

    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[self.pk])
    
    

    class Meta:
        ordering = ['-id']
        # python manage.py shell_plus --print-sql을 이용하여 좀 더 편하게 볼 수 있다.
        # 실행 시킨 후, from instagram.models import Post import 해줘야 한다.

    # 모델에 정의되어 있지 않아도 함수로 list_display 가능.
    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메세지 글자 수"


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, limit_choices_to={'is_public': True})
    # post = models.ForeignKey('instagram.Post', on_delete=models.CASCADE) 문자열을 이용하여 다른 앱을 import 하지 않고 사용 가능하다.
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # post_set = models.ManyToManyField(Post)
    
    def __str__(self):
        return self.name

inflearn/instagram/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'photo', 'tag_set', 'is_public']
        # exclude = [] # 필드를 제외시키는 것.

inflearn/instagram/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm
from .models import Post
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, CreateView, UpdateView, DeleteView


# @login_required
# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user # 현재 로그인 User Instance
#             post.save()

#             messages.success(request, '포스팅을 저장했습니다.')
#             return redirect(post)
#     else:
#         form = PostForm()

#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': None,
#     })


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user

        messages.success(self.request, '포스팅을 저장했습니다.')
        return super().form_valid(form)

post_new = PostCreateView.as_view()



# @login_required
# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)

#     # 작성자 확인
#     if post.author != request.user:
#         messages.error(request, '작성자만 수정할 수 있습니다.')
#         return redirect(post)

#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES, instance=post)

#         if form.is_valid():
#             post = form.save()
#             messages.success(request, '포스팅을 수정했습니다.')
#             return redirect(post)
#     else:
#         form = PostForm(instance=post)

#     return render(request, 'instagram/post_form.html', {
#         'form': form,
#         'post': post,
#     })


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        messages.success(self.request, '포스팅을 수정했습니다.')

        return super().form_valid(form)

post_edit = PostUpdateView.as_view()


# @login_required
# def post_delete(request, pk):
#     post = get_object_or_404(Post, pk=pk)

#     if request.method == 'POST':
#         post.delete()
#         messages.success(request, '포스팅을 삭제했습니다.')

#         return redirect('instagram:post_list')

#     return render(request, 'instagram/post_confirm_delete.html', {
#         'post': post,
#     })

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    # success_url = '/instagram/'
    success_url = reverse_lazy('instagram:post_list')

post_delete = PostDeleteView.as_view()


# CBV decorator 방법1
# @method_decorator(login_required(), name='dispatch')
# class PostListView(ListView):
#     model = Post
#     paginate_by = 10


# post_list = PostListView.as_view()


# CBV decorator 방법2
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10

post_list = PostListView.as_view()


# FBV decorator 방법1
# post_list = login_required(ListView.as_view(model=Post, paginate_by=10))


# FBV decorator 방법2
# @login_required()
# def post_list(request):
#     qs = Post.objects.all()
#     q = request.GET.get('q', '')
#     if q:
#         qs = qs.filter(message__icontains=q)
    
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q' : q,
#     })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    '''
    try :
        post = Post.objects.get(pk=pk) # DoesNotExist 예외 
    except Post.DoesNotExist:
        raise Http404
    '''
    post = get_object_or_404(Post, pk=pk)
    
    return render(request, 'instagram/post_detail.html', {
        'post': post,
    })


post_archive = ArchiveIndexView.as_view(model=Post, date_field='created_at', paginate_by=10)

post_archive_year = YearArchiveView.as_view(model=Post, date_field='created_at', make_object_list=True)

inflearn/instagram/templates/instagram/post_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>latest</h2>
    {{ latest }}

    <h2>date_list</h2>
    {% for date in date_list %}
        {{ date.year }}
    {% endfor %}
</body>
</html>

inflearn/instagram/templates/instagram/post_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>year</h2>
    {{ year }}
    <h2>previouse_year</h2>
    {{ previouse_year }}
    <h2>next_year</h2>
    {{ next_year }}
    <h2>date_list</h2>
    {{ date_list }}
    <h2>object_list</h2>
    {{ object_list}}
</body>
</html>

inflearn/instagram/templates/instagram/post_confirm_delete.html
{% extends "instagram/layout.html" %}

{% block content %}
    <form action="" method='post'>
        {% csrf_token %}

        <div class="alert alert-danger">
            정말 삭제하겠습니까?
        </div>
        
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">No</a>
        <input type="submit" value="Yes" class="btn btn-danger"/>

    </form>
{% endblock %}

inflearn/instagram/templates/instagram/post_detail.html
{% extends 'instagram/layout.html' %}

{% block title %}
    Post Detail pk#{{ post.pk }}
{% endblock title %}

{% block content %}
    <h2>Author : {{ post.author }}</h2>
    {% if post.photo %}
        <div>
            <img src="{{ post.photo.url }}"/>
        </div>
    {% endif %}

    {{ post.message | linebreaks }}
    <a href="{% url 'instagram:post_list' %}" class="btn btn-primary">
        목록
    </a>

    <a href="{% url 'instagram:post_edit' post.pk %}" class="btn btn-info">수정</a>
    <a href="{% url 'instagram:post_delete' post.pk %}" class="btn btn-danger">삭제</a>

{% endblock content %}

inflearn/instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} <table>
        {{ form }}
    </table> {% endcomment %}
    {% buttons %}
        <button class="btn btn-primary">저장</button>
    {% endbuttons %}
</form>

    {% if post %}
        <a href="{{ post.get_absolute_url }}" class="btn btn-secondary">내용으로</a>
    {% endif%}

    <a href="{% url "instagram:post_list" %}" class="btn btn-primary">목록</a>

{% endblock %}

inflearn/instagram/templates/instagram/post_list.html
{% extends 'instagram/layout.html' %}
{% load bootstrap4 %}

{% block title %}
    Instagram / Post List
{% endblock title %}

{% block content %}
<form action="" method="get">
    <input type="text" name="q" value="{{ q }}"/>
    <input type="submit" value="검색"/>
</form>

<a href="{% url 'instagram:post_new' %}" class="btn btn-primary btn-block mt-3 mb-3">새 포스팅</a>

<table class="table table-bordered table-hover">
    <tbody>
        {% for post in post_list %}
            <tr>
                <td>
                    {{ post.pk }}
                </td>
                <td>
                    {% if post.photo %}
                        <img src="{{ post.photo.url }}" style="width: 100px;"/>
                    {% else %}
                        No Photo
                    {% endif %}
                </td>
                <td>
                    {% comment %} <a href="{% url "instagram:post_detail" post.pk %}">     {% endcomment %}
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.message }}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% if is_paginated %}
    {% bootstrap_pagination page_obj size="small" justify_content="center" %}
{% endif %}
{% endblock content %}